<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240225024513 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE test (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_id VARCHAR(255) NOT NULL, finish BOOLEAN NOT NULL, test_date DATE NOT NULL DEFAULT current_date, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE test_answers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, correct BOOLEAN NOT NULL, test_id INT NOT NULL, question_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8C9112CE1E5D0459 ON test_answers (test_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8C9112CE1E27F6BF ON test_answers (question_id)');
        $this->addSql('ALTER TABLE test_answers ADD CONSTRAINT FK_8C9112CE1E5D0459 FOREIGN KEY (test_id) REFERENCES test (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE test_answers ADD CONSTRAINT FK_8C9112CE1E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE test_answers DROP CONSTRAINT FK_8C9112CE1E5D0459');
        $this->addSql('ALTER TABLE test_answers DROP CONSTRAINT FK_8C9112CE1E27F6BF');
        $this->addSql('DROP TABLE test');
        $this->addSql('DROP TABLE test_answers');
    }
}
